services:
  - type: web
    name: watch-ads-earn-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: earn_bot
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_IDS
        value: "123456789,987654321"
      - key: BASE_URL
        fromService:
          name: watch-ads-earn-bot
          type: web
          property: url


---
